module.exports = {
  SUCCESS: {
    RESPONSE_CODE: '00',
    MESSAGE: 'SUCCESS',
  },
  UNDEFINED_RESPONSE_CODE: {
    RESPONSE_CODE: '201',
    MESSAGE: 'UNDEFINED_RESPONSE_CODE',
  },
  WRONG_AUTHENTICATION: {
    RESPONSE_CODE: '204',
    MESSAGE: 'WRONG_AUTHENTICATION',
  },
  INVALID_DATA: {
    RESPONSE_CODE: '208',
    MESSAGE: 'INVALID_DATA',
  },
};
