module.exports = {
  SUCCESS: {
    RESPONSE_CODE: '00',
    MESSAGE: 'SUCCESS',
  },
  TRANSACTION_NOT_FOUND: {
    RESPONSE_CODE: '06',
    MESSAGE: 'TRANSACTION NOT FOUND',
  },
  NUMBER_NOT_MATCH_WITH_OPERATOR: {
    RESPONSE_CODE: '16',
    MESSAGE: 'NUMBER NOT MATCH WITH OPERATOR',
  },
  CODE_NOT_FOUND: {
    RESPONSE_CODE: '20',
    MESSAGE: 'CODE NOT FOUND',
  },
  PROCESS: {
    RESPONSE_CODE: '39',
    MESSAGE: 'PROCESS',
  },
  UNDEFINED_RESPONSE_CODE: {
    RESPONSE_CODE: '201',
    MESSAGE: 'UNDEFINED RESPONSE CODE',
  },
  MAXIMUM_1_NUMBER_1_TIME_IN_1_DAY: {
    RESPONSE_CODE: '202',
    MESSAGE: 'MAXIMUM 1 NUMBER 1 TIME IN 1 DAY',
  },
  WRONG_AUTHENTICATION: {
    RESPONSE_CODE: '204',
    MESSAGE: 'WRONG AUTHENTICATION',
  },
  INVALID_DATA: {
    RESPONSE_CODE: '208',
    MESSAGE: 'INVALID DATA',
  },
};
