module.exports = {
  SUCCESS: {
    RESPONSE_CODE: '00',
    MESSAGE: 'SUCCESS',
  },
  INVOICE_HAS_BEEN_PAID: {
    RESPONSE_CODE: '01',
    MESSAGE: 'INVOICE HAS BEEN PAID',
  },
  TRANSACTION_NOT_FOUND: {
    RESPONSE_CODE: '06',
    MESSAGE: 'TRANSACTION NOT FOUND',
  },
  INCORRECT_DESTINATION_NUMBER: {
    RESPONSE_CODE: '14',
    MESSAGE: 'INCORRECT DESTINATION NUMBER',
  },
  NUMBER_NOT_MATCH_WITH_OPERATOR: {
    RESPONSE_CODE: '16',
    MESSAGE: 'NUMBER NOT MATCH WITH OPERATOR',
  },
  CODE_NOT_FOUND: {
    RESPONSE_CODE: '20',
    MESSAGE: 'CODE NOT FOUND',
  },
  PROCESS: {
    RESPONSE_CODE: '39',
    MESSAGE: 'PROCESS',
  },
  PAYMENT_REQUEST_NOT_RECEIVED_YET: {
    RESPONSE_CODE: '42',
    MESSAGE: 'PAYMENT REQUEST HAVEN\'T BEEN RECEIVED',
  },
  TIMEOUT: {
    RESPONSE_CODE: '103',
    MESSAGE: 'TIMEOUT',
  },
  UNDEFINED_RESPONSE_CODE: {
    RESPONSE_CODE: '201',
    MESSAGE: 'UNDEFINED RESPONSE CODE',
  },
  MAXIMUM_1_NUMBER_1_TIME_IN_1_DAY: {
    RESPONSE_CODE: '202',
    MESSAGE: 'MAXIMUM 1 NUMBER 1 TIME IN 1 DAY',
  },
  WRONG_AUTHENTICATION: {
    RESPONSE_CODE: '204',
    MESSAGE: 'WRONG AUTHENTICATION',
  },
  INVALID_DATA: {
    RESPONSE_CODE: '208',
    MESSAGE: 'INVALID DATA',
  },
};
